### ISSUE TITLE
Installation error on raspberry pi 3

### ISSUE THREAD

**Issue by roedeer82** [O-Hahn/node-red-contrib-speakerpi#11]
I get an error when installing the node:

- nodejs v18.2.0.
- node red v2.2.2

`2022-05-30T18:43:06.940Z Installieren : node-red-contrib-speakerpi 0.0.43

2022-05-30T18:43:07.189Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-speakerpi@0.0.43
2022-05-30T18:43:11.291Z [err] npm
2022-05-30T18:43:11.295Z [err]  
2022-05-30T18:43:11.295Z [err] WARN config production Use `--omit=dev` instead.
2022-05-30T18:43:34.839Z [err] npm
2022-05-30T18:43:34.840Z [err]  ERR! code 1
2022-05-30T18:43:34.841Z [err] npm
2022-05-30T18:43:34.843Z [err]  
2022-05-30T18:43:34.844Z [err] ERR! path /mnt/dietpi_userdata/node-red/node_modules/speaker
2022-05-30T18:43:34.858Z [err] npm 
2022-05-30T18:43:34.859Z [err] ERR! command failed
2022-05-30T18:43:34.859Z [err] npm ERR! 
2022-05-30T18:43:34.859Z [err] command sh -c node-gyp rebuild
2022-05-30T18:43:34.860Z [err] npm ERR!
2022-05-30T18:43:34.861Z [err]  make: Entering directory '/mnt/dietpi_userdata/node-red/node_modules/speaker/build'
2022-05-30T18:43:34.861Z [err] npm ERR!   CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
2022-05-30T18:43:34.861Z [err] npm
2022-05-30T18:43:34.861Z [err]  ERR! make: Leaving directory '/mnt/dietpi_userdata/node-red/node_modules/speaker/build'
2022-05-30T18:43:34.863Z [err] npm 
2022-05-30T18:43:34.864Z [err] ERR! gyp info it worked if it ends with ok
2022-05-30T18:43:34.864Z [err] npm ERR!
2022-05-30T18:43:34.865Z [err]  gyp info using node-gyp@9.0.0
2022-05-30T18:43:34.865Z [err] npm ERR! gyp info using node@18.2.0 | linux | arm
2022-05-30T18:43:34.865Z [err] npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
2022-05-30T18:43:34.865Z [err] npm ERR!
2022-05-30T18:43:34.866Z [err]  gyp info spawn /usr/bin/python3
2022-05-30T18:43:34.866Z [err] npm ERR! gyp info spawn args [
2022-05-30T18:43:34.866Z [err] npm
2022-05-30T18:43:34.866Z [err]  ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2022-05-30T18:43:34.866Z [err] npm ERR!
2022-05-30T18:43:34.867Z [err]  gyp info spawn args   'binding.gyp',
2022-05-30T18:43:34.867Z [err] npm ERR! gyp info spawn args   '-f',
2022-05-30T18:43:34.867Z [err] npm ERR!
2022-05-30T18:43:34.867Z [err]  gyp info spawn args   'make',
2022-05-30T18:43:34.867Z [err] npm ERR! gyp info spawn args   '-I',
2022-05-30T18:43:34.867Z [err] npm
2022-05-30T18:43:34.867Z [err]  ERR! gyp info spawn args   '/mnt/dietpi_userdata/node-red/node_modules/speaker/build/config.gypi',
2022-05-30T18:43:34.867Z [err] npm ERR!
2022-05-30T18:43:34.868Z [err]  gyp info spawn args   '-I',
2022-05-30T18:43:34.868Z [err] npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2022-05-30T18:43:34.868Z [err] npm ERR! gyp info spawn args   '-I',
2022-05-30T18:43:34.868Z [err] npm ERR!
2022-05-30T18:43:34.869Z [err]  gyp info spawn args   '/mnt/dietpi_userdata/node-red/.cache/node-gyp/18.2.0/include/node/common.gypi',
2022-05-30T18:43:34.869Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2022-05-30T18:43:34.869Z [err] npm
2022-05-30T18:43:34.869Z [err]  ERR! gyp info spawn args   '-Dvisibility=default',
2022-05-30T18:43:34.869Z [err] npm ERR!
2022-05-30T18:43:34.869Z [err]  gyp info spawn args   '-Dnode_root_dir=/mnt/dietpi_userdata/node-red/.cache/node-gyp/18.2.0',
2022-05-30T18:43:34.869Z [err] npm ERR!
2022-05-30T18:43:34.870Z [err]  gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
2022-05-30T18:43:34.870Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/mnt/dietpi_userdata/node-red/.cache/node-gyp/18.2.0/<(target_arch)/node.lib',
2022-05-30T18:43:34.870Z [err] npm
2022-05-30T18:43:34.870Z [err]  ERR! gyp info spawn args   '-Dmodule_root_dir=/mnt/dietpi_userdata/node-red/node_modules/speaker',
2022-05-30T18:43:34.870Z [err] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2022-05-30T18:43:34.871Z [err] npm ERR! gyp info spawn args   '--depth=.',
2022-05-30T18:43:34.871Z [err] npm
2022-05-30T18:43:34.871Z [err]  ERR! gyp info spawn args   '--no-parallel',
2022-05-30T18:43:34.871Z [err] npm ERR!
2022-05-30T18:43:34.871Z [err]  gyp info spawn args   '--generator-output',
2022-05-30T18:43:34.871Z [err] npm ERR! gyp info spawn args   'build',
2022-05-30T18:43:34.871Z [err] npm
2022-05-30T18:43:34.872Z [err]  ERR! gyp info spawn args   '-Goutput_dir=.'
2022-05-30T18:43:34.872Z [err] npm ERR!
2022-05-30T18:43:34.873Z [err]  gyp info spawn args ]
2022-05-30T18:43:34.873Z [err] npm ERR! gyp info spawn make
2022-05-30T18:43:34.873Z [err] npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2022-05-30T18:43:34.873Z [err] npm ERR! In file included from ../deps/mpg123/src/libmpg123/compat.h:22,
2022-05-30T18:43:34.873Z [err] npm 
2022-05-30T18:43:34.873Z [err] ERR!                  from ../deps/mpg123/src/mpg123app.h:17,
2022-05-30T18:43:34.873Z [err] npm ERR!
2022-05-30T18:43:34.874Z [err]                   from ../deps/mpg123/src/output/alsa.c:10:
2022-05-30T18:43:34.874Z [err] npm ERR! /usr/include/stdlib.h:25:10: fatal error: bits/libc-header-start.h: No such file or directory
2022-05-30T18:43:34.874Z [err] npm 
2022-05-30T18:43:34.874Z [err] ERR!  #include <bits/libc-header-start.h>
2022-05-30T18:43:34.874Z [err] npm ERR!           ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-05-30T18:43:34.874Z [err] npm
2022-05-30T18:43:34.875Z [err]  ERR! compilation terminated.
2022-05-30T18:43:34.875Z [err] npm ERR!
2022-05-30T18:43:34.875Z [err]  make: *** [deps/mpg123/output.target.mk:126: Release/obj.target/output/deps/mpg123/src/output/alsa.o] Error 1
2022-05-30T18:43:34.875Z [err] npm ERR! gyp ERR! build error 
2022-05-30T18:43:34.875Z [err] npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
2022-05-30T18:43:34.875Z [err] npm
2022-05-30T18:43:34.876Z [err]  ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2022-05-30T18:43:34.876Z [err] npm 
2022-05-30T18:43:34.876Z [err] ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-05-30T18:43:34.876Z [err] npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
2022-05-30T18:43:34.877Z [err] npm ERR! gyp ERR! System Linux 5.10.103-v7+
2022-05-30T18:43:34.877Z [err] npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-05-30T18:43:34.877Z [err] npm
2022-05-30T18:43:34.877Z [err]  ERR! gyp ERR! cwd /mnt/dietpi_userdata/node-red/node_modules/speaker
2022-05-30T18:43:34.877Z [err] npm 
2022-05-30T18:43:34.877Z [err] ERR! gyp ERR! node -v v18.2.0
2022-05-30T18:43:34.877Z [err] npm ERR!
2022-05-30T18:43:34.878Z [err]  gyp ERR! node-gyp -v v9.0.0
2022-05-30T18:43:34.878Z [err] npm ERR!
2022-05-30T18:43:34.878Z [err]  gyp ERR! not ok
2022-05-30T18:43:34.904Z [err] 
2022-05-30T18:43:34.904Z [err] npm ERR! A complete log of this run can be found in:
2022-05-30T18:43:34.904Z [err] npm ERR!     /mnt/dietpi_userdata/node-red/.npm/_logs/2022-05-30T18_43_11_083Z-debug-0.log
2022-05-30T18:43:34.945Z rc=1`

Any possible solution?

**Comment by juggledad** [comment]
Try rolling Node.js back to v16 

And are you using a DietPi?

**Comment by roedeer82** [comment]
> Try rolling Node.js back to v16
> 
> And are you using a DietPi?

I'm using Node.js v18 on Dietpi. I will get back to v16 and try again.

**Comment by roedeer82** [comment]
with Node.js v16.15 I still get errors:
`2022-06-01T17:38:30.659Z Installieren : node-red-contrib-speakerpi 0.0.43

2022-06-01T17:37:58.123Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-speakerpi@0.0.43
2022-06-01T17:38:25.139Z [err] npm
2022-06-01T17:38:25.141Z [err]  
2022-06-01T17:38:25.144Z [err] ERR!
2022-06-01T17:38:25.145Z [err]  
2022-06-01T17:38:25.146Z [err] code
2022-06-01T17:38:25.147Z [err]  1
2022-06-01T17:38:25.150Z [err] npm
2022-06-01T17:38:25.151Z [err]  
2022-06-01T17:38:25.152Z [err] ERR!
2022-06-01T17:38:25.153Z [err]  
2022-06-01T17:38:25.154Z [err] path
2022-06-01T17:38:25.155Z [err]  /mnt/dietpi_userdata/node-red/node_modules/speaker
2022-06-01T17:38:25.174Z [err] npm
2022-06-01T17:38:25.175Z [err]  
2022-06-01T17:38:25.176Z [err] ERR!
2022-06-01T17:38:25.177Z [err]  command failed
2022-06-01T17:38:25.178Z [err] npm
2022-06-01T17:38:25.179Z [err]  
2022-06-01T17:38:25.180Z [err] ERR!
2022-06-01T17:38:25.180Z [err]  
2022-06-01T17:38:25.181Z [err] command
2022-06-01T17:38:25.182Z [err]  sh -c node-gyp rebuild
2022-06-01T17:38:25.183Z [err] npm
2022-06-01T17:38:25.184Z [err]  
2022-06-01T17:38:25.184Z [err] ERR!
2022-06-01T17:38:25.185Z [err]  make: Entering directory '/mnt/dietpi_userdata/node-red/node_modules/speaker/build'
2022-06-01T17:38:25.186Z [err] npm
2022-06-01T17:38:25.188Z [err]  
2022-06-01T17:38:25.188Z [err] ERR!
2022-06-01T17:38:25.189Z [err]    CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
2022-06-01T17:38:25.191Z [err] npm ERR! make: Leaving directory '/mnt/dietpi_userdata/node-red/node_modules/speaker/build'
2022-06-01T17:38:25.192Z [err] npm ERR!
2022-06-01T17:38:25.193Z [err]  gyp info it worked if it ends with ok
2022-06-01T17:38:25.193Z [err] npm ERR! gyp info using node-gyp@9.0.0
2022-06-01T17:38:25.193Z [err] npm 
2022-06-01T17:38:25.193Z [err] ERR! gyp info using node@16.15.0 | linux | arm
2022-06-01T17:38:25.193Z [err] npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
2022-06-01T17:38:25.193Z [err] npm
2022-06-01T17:38:25.194Z [err]  ERR! gyp info spawn /usr/bin/python3
2022-06-01T17:38:25.194Z [err] npm ERR! gyp info spawn args [
2022-06-01T17:38:25.194Z [err] npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2022-06-01T17:38:25.194Z [err] npm ERR! gyp info spawn args   'binding.gyp',
2022-06-01T17:38:25.195Z [err] npm ERR! gyp info spawn args   '-f',
2022-06-01T17:38:25.195Z [err] npm ERR! gyp info spawn args   'make',
2022-06-01T17:38:25.195Z [err] npm ERR! gyp info spawn args   '-I',
2022-06-01T17:38:25.195Z [err] npm ERR! gyp info spawn args   '/mnt/dietpi_userdata/node-red/node_modules/speaker/build/config.gypi',
2022-06-01T17:38:25.196Z [err] npm ERR! gyp info spawn args   '-I',
2022-06-01T17:38:25.196Z [err] npm ERR!
2022-06-01T17:38:25.196Z [err]  gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2022-06-01T17:38:25.196Z [err] npm ERR! gyp info spawn args   '-I',
2022-06-01T17:38:25.196Z [err] npm ERR!
2022-06-01T17:38:25.197Z [err]  gyp info spawn args   '/mnt/dietpi_userdata/node-red/.cache/node-gyp/16.15.0/include/node/common.gypi',
2022-06-01T17:38:25.197Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2022-06-01T17:38:25.197Z [err] npm ERR!
2022-06-01T17:38:25.197Z [err]  gyp info spawn args   '-Dvisibility=default',
2022-06-01T17:38:25.197Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/mnt/dietpi_userdata/node-red/.cache/node-gyp/16.15.0',
2022-06-01T17:38:25.197Z [err] npm
2022-06-01T17:38:25.198Z [err]  ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
2022-06-01T17:38:25.198Z [err] npm ERR!
2022-06-01T17:38:25.198Z [err]  gyp info spawn args   '-Dnode_lib_file=/mnt/dietpi_userdata/node-red/.cache/node-gyp/16.15.0/<(target_arch)/node.lib',
2022-06-01T17:38:25.198Z [err] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/mnt/dietpi_userdata/node-red/node_modules/speaker',
2022-06-01T17:38:25.198Z [err] npm 
2022-06-01T17:38:25.198Z [err] ERR! gyp info spawn args   '-Dnode_engine=v8',
2022-06-01T17:38:25.198Z [err] npm ERR! gyp info spawn args   '--depth=.',
2022-06-01T17:38:25.199Z [err] npm ERR! gyp info spawn args   '--no-parallel',
2022-06-01T17:38:25.199Z [err] npm ERR!
2022-06-01T17:38:25.199Z [err]  gyp info spawn args   '--generator-output',
2022-06-01T17:38:25.199Z [err] npm ERR! gyp info spawn args   'build',
2022-06-01T17:38:25.199Z [err] npm
2022-06-01T17:38:25.200Z [err]  ERR! gyp info spawn args   '-Goutput_dir=.'
2022-06-01T17:38:25.200Z [err] npm ERR!
2022-06-01T17:38:25.200Z [err]  gyp info spawn args ]
2022-06-01T17:38:25.200Z [err] npm ERR! gyp info spawn make
2022-06-01T17:38:25.200Z [err] npm 
2022-06-01T17:38:25.201Z [err] ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2022-06-01T17:38:25.201Z [err] npm ERR! In file included from ../deps/mpg123/src/libmpg123/compat.h:22,
2022-06-01T17:38:25.201Z [err] npm
2022-06-01T17:38:25.201Z [err]  ERR!                  from ../deps/mpg123/src/mpg123app.h:17,
2022-06-01T17:38:25.201Z [err] npm ERR!                  from ../deps/mpg123/src/output/alsa.c:10:
2022-06-01T17:38:25.202Z [err] npm ERR! /usr/include/stdlib.h:25:10: fatal error: bits/libc-header-start.h: No such file or directory
2022-06-01T17:38:25.202Z [err] npm 
2022-06-01T17:38:25.202Z [err] ERR!  #include <bits/libc-header-start.h>
2022-06-01T17:38:25.202Z [err] npm ERR!           ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-06-01T17:38:25.202Z [err] npm ERR! compilation terminated.
2022-06-01T17:38:25.202Z [err] npm ERR!
2022-06-01T17:38:25.203Z [err]  make: *** [deps/mpg123/output.target.mk:126: Release/obj.target/output/deps/mpg123/src/output/alsa.o] Error 1
2022-06-01T17:38:25.203Z [err] npm ERR! gyp ERR! build error 
2022-06-01T17:38:25.203Z [err] npm 
2022-06-01T17:38:25.203Z [err] ERR! gyp ERR! stack Error: `make` failed with exit code: 2
2022-06-01T17:38:25.203Z [err] npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2022-06-01T17:38:25.203Z [err] npm
2022-06-01T17:38:25.204Z [err]  ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
2022-06-01T17:38:25.204Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
2022-06-01T17:38:25.204Z [err] npm ERR! gyp ERR! System Linux 5.10.103-v7+
2022-06-01T17:38:25.204Z [err] npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-06-01T17:38:25.205Z [err] npm ERR! gyp ERR! cwd /mnt/dietpi_userdata/node-red/node_modules/speaker
2022-06-01T17:38:25.205Z [err] npm ERR!
2022-06-01T17:38:25.205Z [err]  gyp ERR! node -v v16.15.0
2022-06-01T17:38:25.205Z [err] npm ERR! gyp ERR! node-gyp -v v9.0.0
2022-06-01T17:38:25.205Z [err] npm
2022-06-01T17:38:25.206Z [err]  ERR! gyp ERR! not ok
2022-06-01T17:38:25.217Z [err] 
2022-06-01T17:38:25.219Z [err] npm ERR!
2022-06-01T17:38:25.219Z [err]  A complete log of this run can be found in:
2022-06-01T17:38:25.219Z [err] npm ERR!     /mnt/dietpi_userdata/node-red/.npm/_logs/2022-06-01T17_38_00_248Z-debug-0.log
2022-06-01T17:38:25.262Z rc=1`

**Comment by juggledad** [comment]
1) did you do 'sudo apt-get install libasound2-dev'?
2) Are you in the .node-red directory when you try the `node-red-contrib-speakerpi` install?
3) are you using the command 'npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-speakerpi@0.0.43' if so, why are you not using the command in the instructions?

This could be an issue with DietPi missing things that the node needs to compile.
